import { useEffect, useState } from 'react';
import './brand-site.css';
import { GoldenHero } from './GoldenSite.jsx';

const audiences = [
  ['Students', 'Your potential deserves a starting point.', 'Find first jobs, internships, graduate programmes and entry-level opportunities across tech, business and professional career paths.'],
  ['Fresh graduates', 'From education to your next chapter.', 'Turn your learning and experience into a confident first step into the professional job market.'],
  ['Early-career professionals', 'Make room for what comes next.', 'Explore better opportunities, higher-level positions, international roles and new industries with a plan for your growth.'],
  ['Job changers', 'Make your next move a considered one.', 'Get help with CV positioning, target roles, job matching, application strategy, interview preparation and offer comparison.'],
  ['Career changers', 'A new direction. A story that connects.', 'Identify your current and transferable skills, understand the gaps, explore target roles and build a credible transition story.'],
  ['Passive job seekers', 'Stay open to the right opportunity.', 'Keep building your career while you work, with focused support to recognise the opportunity that is worth your next move.'],
];
const journey = [
 ['Discover', 'Discover your direction', 'Understand your goals, experience, skills, target roles, industries, locations and career expectations.', 'Clarity on where you want to go.'],
 ['Review', 'Review your profile', 'Assess your CV, LinkedIn profile, experience and skills to identify gaps and opportunities.', 'Know what needs improvement.'],
 ['Position', 'Build your positioning', 'Define your target roles, industries, transferable skills and professional story.', 'A clear career positioning strategy.'],
 ['Optimise', 'Optimise your CV & profile', 'Strengthen your CV, LinkedIn, cover letters and application materials for your target roles.', 'A stronger, market-ready profile.'],
 ['Match', 'Find relevant opportunities', 'Identify live opportunities that align with your skills, experience, location and career goals.', 'A focused job-search pipeline.'],
 ['Apply', 'Apply strategically', 'Tailor applications, support submissions and track your applications throughout the process.', 'Less random applying, more targeted applications.'],
 ['Prepare', 'Prepare for interviews', 'Practise company-specific, role-specific, technical and behavioural interviews with useful feedback.', 'Greater interview readiness and confidence.'],
 ['Progress', 'Navigate offers & next steps', 'Understand the role, compensation, progression opportunities and next steps before making your decision.', 'Make an informed career move.'],
 ['Grow', 'Keep building your career', 'Get support as you transition into your new role and plan your longer-term career growth.', 'Move from job search to career progression.'],
];
const process = [['↗', 'Know your direction', "Stop applying everywhere. Start knowing where you’re going."], ['✳', 'Build your brand', 'Turn your CV from “just another CV” into a profile recruiters notice.'], ['◎', 'Find your fit', 'Less job-board scrolling. More opportunities that make sense for you.'], ['↗', 'Make your move', 'Right role. Right CV. Right application.'], ['◌', 'Own the interview', 'Prepare smarter. Walk in with confidence.'], ['✦', 'Land & level up', "Your first job isn’t the finish line. It’s the next chapter."]];
const serviceGroups = [
 ['A little clarity.', 'Find your direction', ['Career counselling', 'Job-search strategy', 'Skill-gap identification', 'Professional positioning advice']],
 ['A stronger story.', 'Build your brand', ['Tailored CV & cover letter', 'LinkedIn profile enhancement', 'Portfolio building']],
 ['A confident next step.', 'Make your move', ['Quality job applications', 'Mock interviews', 'Interview support', 'Network connection']],
];
function LinkButton({ children = 'Start your 15-day free trial', light = false }) { return <a className={`ac-button ${light ? 'ac-button-light' : ''}`} href="/contact?trial=1">{children}<span aria-hidden="true">↗</span></a>; }
function Brand() { return <img className="ac-logo" src="/brand/aurrum-careers-transparent.png" alt="Aurrum Careers" width="2171" height="724" />; }
function Endnote() { return <section className="ac-end"><p className="ac-kicker">YOUR NEXT CHAPTER STARTS HERE</p><h2>Great things start<br />with a little <em>direction.</em></h2><LinkButton light /><p>15 days to explore a smarter way forward.</p><span className="ac-end-star" aria-hidden="true">✳</span></section>; }
function Home() {
 const [audience, setAudience] = useState(0);
 return <>
  <GoldenHero />
  <section className="ac-hero ac-wrap" hidden>
   <div className="ac-hero-copy"><p className="ac-kicker"><i /> A LITTLE DIRECTION. A WORLD OF POSSIBILITY.</p><h1>Your personalised<br />career <em>companion.</em></h1><p className="ac-hero-sub">From finding the right role to<br />preparing for the interview.</p><p className="ac-hero-desc">Less scrolling. More direction.<br />Smarter applications. Better opportunities.</p><div className="ac-actions"><LinkButton /><a className="ac-text-link" href="#services">Explore our support <span>↓</span></a></div><p className="ac-trial-note"><span>✦</span> Real people. Personal support. Your next chapter.</p></div>
   <div className="ac-poster" aria-label="An abstract career path moving upward, with the words Your future is an open book."><div className="ac-poster-top">AURRUM / A NEW PERSPECTIVE<span>↗</span></div><span className="ac-sun" /><div className="ac-book"><div className="ac-book-left">YOUR<br />NEXT<br /><b>CHAPTER.</b></div><div className="ac-book-right"><span>↗</span><small>It starts<br />with you.</small></div></div><div className="ac-book-shadow"/><div className="ac-poster-bottom"><h2>Your future is<br />an open book.</h2><span className="ac-poster-square" /></div><p>A little support can change the whole story.</p></div>
  </section>
  <div className="ac-belief"><span>BUILT AROUND YOU</span><p>Human support.<i />Clear direction.<i />Real possibility.</p><span aria-hidden="true">✳</span></div>
  <section id="services" className="ac-section ac-wrap"><div className="ac-heading"><div><p className="ac-kicker">HOW WE HELP</p><h2>Big ambitions.<br /><em>Practical support.</em></h2></div><p>Your career is personal. Your support should be too.<br />We help connect where you are with where you want to go.</p></div><div className="ac-services">{serviceGroups.map(([eyebrow, title, items], i) => <article key={title}><span className="ac-service-symbol" aria-hidden="true">{['↗', '✳', '◎'][i]}</span><p className="ac-kicker">{eyebrow}</p><h3>{title}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><a href="/contact">Let’s talk about you <span>↗</span></a></article>)}</div></section>
  <section className="ac-audience ac-section"><div className="ac-wrap ac-audience-grid"><div><p className="ac-kicker">WHEREVER YOU ARE IN YOUR CAREER</p><h2>There’s a next step<br /><em>for everyone.</em></h2><p>Starting out, stepping up or changing direction.<br />We meet you where you are.</p><div className="ac-audience-options" role="group" aria-label="Choose your career stage">{audiences.map(([title], i) => <button key={title} aria-pressed={audience === i} onClick={() => setAudience(i)}>{title}<span>↗</span></button>)}</div></div><article className="ac-audience-card"><span className="ac-card-star" aria-hidden="true">✳</span><p className="ac-kicker">{audiences[audience][0]}</p><h3>{audiences[audience][1]}</h3><p>{audiences[audience][2]}</p><a className="ac-text-link" href="/contact">Find your starting point <span>↗</span></a></article></div></section>
  <section className="ac-section ac-wrap"><div className="ac-heading"><div><p className="ac-kicker">THE PROCESS</p><h2>Less guesswork.<br /><em>More forward.</em></h2></div><p>A thoughtful approach to every stage of your search.<br />One clear route to your next chapter.</p></div><div className="ac-process">{process.map(([symbol, title, copy]) => <article key={title}><span aria-hidden="true">{symbol}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="ac-journey ac-section"><div className="ac-wrap ac-journey-grid"><div><p className="ac-kicker">YOUR CANDIDATE JOURNEY</p><h2>From “what’s next?”<br />to <em>“I’m ready.”</em></h2><p>Discover → Review → Position → Optimise → Match → Apply → Prepare → Progress → Grow</p><p>Explore each step of your journey.</p></div><div className="ac-steps">{journey.map(([short, title, copy, outcome], i) => <details key={short} open={i === 0 ? true : undefined}><summary>{short}<span aria-hidden="true">+</span></summary><div><h3>{title}</h3><p>{copy}</p><p className="ac-outcome">↗ {outcome}</p></div></details>)}</div></div></section><Endnote />
 </>;
}
function About() { return <><section className="ac-wrap ac-about-hero"><p className="ac-kicker">ABOUT AURRUM CAREERS</p><h1>Your job search<br />deserves <em>better.</em></h1><div className="ac-about-intro"><span className="ac-about-symbol" aria-hidden="true">✳</span><p>Better than a browser tab full of rejection emails. Better than sending CV after CV, hitting “submit”, and waiting endlessly.<br /><strong>Job hunting shouldn’t feel like screaming into the void.</strong></p></div></section><section className="ac-story ac-section"><div className="ac-wrap ac-story-grid"><h2>That’s why<br />we built<br /><em>Aurrum Careers.</em></h2><div><p>We’re not another job board or a black hole for your resume. We’re your <strong>personalised career companion</strong>, combining real human support with a smarter approach to your job search.</p><p>We take the time to understand where you want to go, what you bring to the table, and which opportunities actually make sense for you.</p><p>From refining your CV and matching you with relevant roles to supporting your applications and preparing you for interviews, we’re with you through every step.</p></div></div></section><section className="ac-section ac-wrap"><p className="ac-kicker">THE DIFFERENCE</p><h2>Real support.<br /><em>No empty promises.</em></h2><div className="ac-process ac-difference">{[['Direction, before volume.', 'No applying to hundreds of roles and hoping something sticks. A focused search starts with understanding you.'], ['People, before profiles.', 'You’re not just another resume in a pile. Your experience, ambitions and story shape the support you receive.'], ['Honesty, at every step.', 'No fake promises. No guaranteed-job nonsense. Just smarter applications and real support when it matters.']].map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="ac-about-quote">You’re someone’s next great hire.<br /><em>Let’s help them find you.</em></p></section><Endnote /></>; }
function Contact() {
 const [saved, setSaved] = useState(false);
 const email = import.meta.env.VITE_CONTACT_EMAIL || 'care@aurrum.co';
 function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = `Name: ${form.get('name')}\nEmail: ${form.get('email')}\nCareer stage: ${form.get('stage')}\nInterest: ${form.get('interest')}\n\n${form.get('message')}`; if (email) { window.location.href = `mailto:${email}?subject=${encodeURIComponent('Aurrum Careers enquiry')}&body=${encodeURIComponent(body)}`; } else { const url = URL.createObjectURL(new Blob([body], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'my-aurrum-career-brief.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } setSaved(true); }
 return <section className="ac-wrap ac-contact"><div><p className="ac-kicker">LET’S TALK ABOUT YOUR NEXT CHAPTER</p><h1>A little hello.<br /><em>A new beginning.</em></h1><p>Tell us where you are and where you’d like to go.<br />We’ll start with you.</p><div className="ac-contact-note"><span aria-hidden="true">↗</span><h3>15 days. A fresh perspective.</h3><p>Explore personalised career support with a 15-day free trial. Take the first step towards a more focused search.</p></div></div><form onSubmit={submit}><h2>Your next step starts here.</h2><p>A few details to help us understand your journey.</p><label>Full name<input name="name" autoComplete="name" placeholder="Your full name" required maxLength={120}/></label><label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required /></label><div className="ac-form-row"><label>Your career stage<select name="stage" required defaultValue=""><option value="" disabled>Select your stage</option>{audiences.map(([title]) => <option key={title}>{title}</option>)}</select></label><label>I’m interested in<select name="interest" defaultValue={new URLSearchParams(location.search).has('trial') ? '15-day free trial' : 'Career support'}><option>15-day free trial</option><option>Career support</option><option>CV & profile support</option><option>Interview preparation</option></select></label></div><label>What would you like help with?<textarea name="message" rows="4" placeholder="A new role, a different direction, a stronger CV…" required maxLength={4000}/></label><p className="ac-form-note">{email ? 'Your email app will open with your enquiry ready to send.' : 'Enquiries are not connected yet. You can save your details as a career brief; nothing will be sent or stored on this site.'}</p><button className="ac-button" type="submit">{email ? 'Prepare my enquiry' : 'Save my career brief'}<span>↗</span></button>{saved && <p className="ac-form-status" role="status">{email ? 'Your enquiry is ready in your email app. Send it there to contact Aurrum Careers.' : 'Your career brief has been downloaded. Your enquiry has not been sent.'}</p>}</form></section>;
}
export default function BrandSite() {
 const [menu, setMenu] = useState(false);
 const page = location.pathname.replace(/\/$/, '') || '/';
 useEffect(() => { document.title = `${page === '/about' ? 'About' : page === '/contact' ? 'Contact' : 'Your personalised career companion'} | Aurrum Careers`; }, [page]);
 return <div className="ac-site"><a className="ac-skip" href="#main-content">Skip to content</a><header className="ac-header ac-wrap"><a href="/" aria-label="Aurrum Careers home"><Brand /></a><button className="ac-menu" aria-expanded={menu} aria-controls="ac-nav" onClick={() => setMenu(!menu)}>{menu ? 'Close −' : 'Menu +'}</button><nav id="ac-nav" className={menu ? 'ac-nav-open' : ''} aria-label="Main navigation">{[['/', 'Home'], ['/about', 'About'], ['/contact', 'Contact']].map(([href, label]) => <a key={href} href={href} aria-current={page === href ? 'page' : undefined}>{label}</a>)}</nav><a className="ac-header-cta" href="/contact?trial=1">Let’s get started <span>↗</span></a></header><main id="main-content">{page === '/' ? <Home /> : page === '/about' ? <About /> : page === '/contact' ? <Contact /> : <section className="ac-section ac-wrap"><h1>Let’s find your way.</h1><p>This page isn’t here.</p><a className="ac-button" href="/">Back to home ↗</a></section>}</main><footer className="ac-footer ac-wrap"><div><a href="/" aria-label="Aurrum Careers home"><Brand /></a><p>Your career. Your story. Your next chapter.</p></div><div><a href="/">Home</a><a href="/about">About</a><a href="/contact">Contact</a></div><p>© {new Date().getFullYear()} Aurrum Careers<br />A little direction goes a long way.</p></footer></div>;
}
